In [1]:
import array

lista = list(range(10))

In [2]:
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arreglo = array.array('i',lista)
arreglo

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
pip install numpy

You should consider upgrading via the '/opt/homebrew/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [6]:
np_integer_array = np.array([1,2,3,4,5])
np_integer_array

array([1, 2, 3, 4, 5])

In [7]:
np_float_array = np.array([4.5,1,2,3,4,5])
np_float_array

array([4.5, 1. , 2. , 3. , 4. , 5. ])

In [8]:
np_int_array = np.array([4.5,1,2,3,4,5],dtype="int")
np_int_array

array([4, 1, 2, 3, 4, 5])

In [9]:
one_to_nine_matrix = np.array([range(i,i+3) for i in [1,4,7]])
one_to_nine_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
zeros = np.zeros(10,dtype='int')
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Matriz de 3 filas y 5 columnas

In [11]:
np.ones((3,5),dtype="float")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.full((2,2),3.14)

array([[3.14, 3.14],
       [3.14, 3.14]])

# Generar un rango
## Inicia en 0, termina en 20, saltos de 2 en 2

In [13]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Inicia en 0, termina en 1 y genera 5 valores equidistantes

In [14]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Aleatoriedad

In [15]:
np.random.seed(0)

bool_

Boolean (True or False) stored as a byte

int_

Default integer type (same as C long; normally either int64 or int32)

intc

Identical to C int (normally int32 or int64)

intp

Integer used for indexing (same as C ssize_t; normally either int32 or int64)

int8

Byte (–128 to 127)

int16

Integer (–32768 to 32767)

int32

Integer (–2147483648 to 2147483647)

int64

Integer (–9223372036854775808 to 9223372036854775807)

uint8

Unsigned integer (0 to 255)

uint16

Unsigned integer (0 to 65535)

uint32

Unsigned integer (0 to 4294967295)

uint64

Unsigned integer (0 to 18446744073709551615)

float_

Shorthand for float64

float16

Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa

float32

Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa

float64

Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa

complex_

Shorthand for complex128

complex64

Complex number, represented by two 32-bit floats

complex128

Complex number, represented by two 64-bit floats

## One-dimensional array

In [16]:
x1 = np.random.randint(10,size=6) # muestra de 6 elementos
x1

array([5, 0, 3, 3, 7, 9])

In [17]:
x1[3]

3

In [18]:
x2 = np.random.randint(10,size=(3,4)) # Matriz o Two dimensional array
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [19]:
print(x2[1][2])
print(x2[1,2])

8
8


In [20]:
x3 = np.random.randint(10,size=(3,4,5)) # Three dimensional array
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [21]:
print("x3 numero dimensiones",x3.ndim)
print("x3 shape",x3.shape)
print("x3 size",x3.size)
print("x3 type",x3.dtype)

x3 numero dimensiones 3
x3 shape (3, 4, 5)
x3 size 60
x3 type int64


In [22]:
print(x3[0][3][1])
print(x3[0,3,1])

3
3


In [23]:
x3[0,3,1] = 5.5

In [24]:
x3[0,3,1]

5

In [25]:
nuevo_arreglo = np.arange(10)

In [26]:
nuevo_arreglo[3:6]

array([3, 4, 5])

In [27]:
nuevo_arreglo[1::2] # Posiciones de 3 en 3

array([1, 3, 5, 7, 9])

In [28]:
nuevo_arreglo[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [29]:
nuevo_arreglo[5::-2] # Desde la posicion 5, disminuye de 2 en 2

array([5, 3, 1])

In [30]:
x2[:3,:3]

array([[3, 5, 2],
       [7, 6, 8],
       [1, 6, 7]])

In [31]:
x3[:3,:3,:3]

array([[[8, 1, 5],
        [9, 4, 3],
        [5, 0, 2]],

       [[0, 1, 9],
        [4, 7, 3],
        [2, 0, 0]],

       [[4, 9, 8],
        [7, 9, 9],
        [7, 2, 0]]])

In [32]:
#obteniendo la primer columa
x2[:,0]

array([3, 7, 1])

In [33]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [34]:
#Obteniendo la tercer columa
x2[:,3]

array([4, 8, 7])

In [35]:
x2[0] # x2[0,:]

array([3, 5, 2, 4])

## Sub-arreglos no generan copias de la información, generan vistas

In [36]:
#Generando una copia
x3_sub_copia = x3[:3,:3,:3].copy()
x3_sub_copia

array([[[8, 1, 5],
        [9, 4, 3],
        [5, 0, 2]],

       [[0, 1, 9],
        [4, 7, 3],
        [2, 0, 0]],

       [[4, 9, 8],
        [7, 9, 9],
        [7, 2, 0]]])

In [37]:
x3_sub = x3[:3,:3,:3]
x3_sub[0,0,0] = 15
x3

array([[[15,  1,  5,  9,  8],
        [ 9,  4,  3,  0,  3],
        [ 5,  0,  2,  3,  8],
        [ 1,  5,  3,  3,  7]],

       [[ 0,  1,  9,  9,  0],
        [ 4,  7,  3,  2,  7],
        [ 2,  0,  0,  4,  5],
        [ 5,  6,  8,  4,  1]],

       [[ 4,  9,  8,  1,  1],
        [ 7,  9,  9,  3,  6],
        [ 7,  2,  0,  3,  5],
        [ 9,  4,  4,  6,  4]]])

# Reshaping of arrays

In [38]:
# El numero de elementos a reformar debe coincidir con la forma
# Por ejemplo: 9 -> 3x3
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
x_array = np.array([1,2,3])
x_array.reshape((1,3))

array([[1, 2, 3]])

In [40]:
x_array

array([1, 2, 3])

# Array concatenation and splitting