In [1]:
import array

lista = list(range(10))

In [2]:
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arreglo = array.array('i',lista)
arreglo

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You should consider upgrading via the '/opt/homebrew/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [10]:
import numpy as np

In [11]:
np_integer_array = np.array([1,2,3,4,5])
np_integer_array

array([1, 2, 3, 4, 5])

In [14]:
np_float_array = np.array([4.5,1,2,3,4,5])
np_float_array

array([4.5, 1. , 2. , 3. , 4. , 5. ])

In [15]:
np_int_array = np.array([4.5,1,2,3,4,5],dtype="int")
np_int_array

array([4, 1, 2, 3, 4, 5])

In [16]:
one_to_nine_matrix = np.array([range(i,i+3) for i in [1,4,7]])
one_to_nine_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
zeros = np.zeros(10,dtype='int')
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Matriz de 3 filas y 5 columnas

In [23]:
np.ones((3,5),dtype="float")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.full((2,2),3.14)

array([[3.14, 3.14],
       [3.14, 3.14]])

# Generar un rango
## Inicia en 0, termina en 20, saltos de 2 en 2

In [25]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Inicia en 0, termina en 1 y genera 5 valores equidistantes

In [26]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])