In [1]:
import numpy as np

In [2]:
data = np.array([1,4,4])
data

array([1, 4, 4])

In [3]:
mean = data.mean()
absolutos = np.absolute(data-mean)
absolutos

array([2., 1., 1.])

In [5]:
mean_absolute_deviation = absolutos.mean()
mean_absolute_deviation

1.3333333333333333

# Standar deviation

In [13]:
deviations = data-data.mean()
squared_deviations = deviations**2
variance = squared_deviations.mean()
variance

2.0

In [14]:
standard_deviation = np.sqrt(variance)
standard_deviation

1.4142135623730951

In [15]:
data.std()

1.4142135623730951

In [16]:
data

array([1, 4, 4])

# Median absolute deviation from the median

In [4]:
data = np.array([4,3,2,1,5,6])
median = np.median(data)
median

3.5

In [5]:
MAD = np.median(np.absolute(data-median))
MAD

1.5

# Estimados basados en Percentiles

In [11]:
array = np.array([10,12,11,13,9,10,11])
p25 = np.quantile(array,0.25)
p75 = np.quantile(array,0.75)

print(p25)
print(p75)

10.0
11.5


In [8]:
iqr = p75-p25
iqr

1.5

# Ejemplo de estimados de variabilidad

In [12]:
import pandas as pd

In [13]:
data = pd.read_csv("../datos.csv")
data

Number        State  Population  Murder rate Abbreviation
0       1      Alabama     4779736          5.7           AL
1       2       Alaska      710231          5.6           AK
2       3      Arizona     6392017          4.7           AZ
3       4     Arkansas     2915918          5.6           AR
4       5   California    37253956          4.4           CA
5       6     Colorado     5029196          2.8           CO
6       7  Connecticut     3574097          2.4           CT
7       8     Delaware      897934          5.8           DE

In [14]:
#standard deviation
data["Population"].std()

12105745.29585633

In [15]:
#IQR
data["Population"].quantile(0.75)-data["Population"].quantile(0.25)

2958479.25

In [17]:
medianPopulation = np.median(data["Population"])
medianPopulation

4176916.5

In [18]:
# MAD
np.median(np.absolute(data["Population"]-medianPopulation))

1738049.5

In [21]:
# standard deviation without california
data.drop([4],axis=0)["Population"].std()

2130507.1183770173