In [1]:
import numpy as np

In [2]:
data = np.array([1,4,4])
data

array([1, 4, 4])

In [3]:
mean = data.mean()
absolutos = np.absolute(data-mean)
absolutos

array([2., 1., 1.])

In [5]:
mean_absolute_deviation = absolutos.mean()
mean_absolute_deviation

1.3333333333333333

# Standar deviation

In [13]:
deviations = data-data.mean()
squared_deviations = deviations**2
variance = squared_deviations.mean()
variance

2.0

In [14]:
standard_deviation = np.sqrt(variance)
standard_deviation

1.4142135623730951

In [15]:
data.std()

1.4142135623730951

In [16]:
data

array([1, 4, 4])

# Median absolute deviation from the median

In [4]:
data = np.array([4,3,2,1,5,6])
median = np.median(data)
median

3.5

In [5]:
MAD = np.median(np.absolute(data-median))
MAD

1.5

# Estimados basados en Percentiles