In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [3]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [4]:
z = [99,99,99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [18]:
grid = np.array([[1,2,3],[4,5,6]])

np.concatenate([grid,[[1,2,3]]])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [15]:
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [19]:
np.vstack([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [20]:
np.hstack([grid,grid])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Splitting arrays

In [24]:
x = [1,2,3,99,3,2,1]

_,x2,_,x4 = np.split(x,[3,4,5])

In [26]:
print(x2,x4)

[99] [2 1]


In [27]:
print(x)

[1, 2, 3, 99, 3, 2, 1]


In [28]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
upper,lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [30]:
left,right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
