# Computation arrays
- Utilizar operaciones vectorizadas (vectorized operations)
- Funciones universales (ufuncs)

In [2]:
import numpy as np

np.random.seed(0)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1 / values[i]

    return output

values = np.random.randint(1,10,size=5)
compute_reciprocals(values)


big_array = np.random.randint(1,100,size = 1000)

%timeit compute_reciprocals(big_array)

134 ms ± 3.25 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
print(1.0/values)

[0.16666667 1.         0.25       0.25       0.125     ]


In [4]:
print(compute_reciprocals(values))

[0.16666667 1.         0.25       0.25       0.125     ]


In [5]:
%timeit (1.0/big_array)

817 µs ± 48.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [2]:
import numpy as np

In [4]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
print(x+5)
print(x-5)
print(x*2)
print(x/2)

[ 5  6  7  8  9 10 11 12 13 14]
[-5 -4 -3 -2 -1  0  1  2  3  4]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [8]:
print(-x)
print(x**2)
print(x%2)

[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 0  1  4  9 16 25 36 49 64 81]
[0 1 0 1 0 1 0 1 0 1]


In [9]:
-(0.5*x+1)**2

array([ -1.  ,  -2.25,  -4.  ,  -6.25,  -9.  , -12.25, -16.  , -20.25,
       -25.  , -30.25])

In [11]:
# Estas operaciones son equivalentes
np.add(x,2)
x+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
datos = np.array([-2,-1,0,1,2])

abs(datos)

array([2, 1, 0, 1, 2])

In [13]:
np.absolute(datos)

array([2, 1, 0, 1, 2])

In [15]:
# Utilizando el alias
np.abs(datos)

array([2, 1, 0, 1, 2])

In [16]:
# Funciones trigonométricas
theta = np.linspace(0,np.pi,3)
theta

array([0.        , 1.57079633, 3.14159265])

In [18]:
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [20]:
print(np.arcsin(theta))
print(np.arccos(theta))
print(np.arctan(theta))

[ 0. nan nan]
[1.57079633        nan        nan]
[0.         1.00388482 1.26262726]


/var/folders/sb/30311bq16l911lpqttfpzgdw0000gn/T/ipykernel_68533/662710321.py:1: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(theta))
/var/folders/sb/30311bq16l911lpqttfpzgdw0000gn/T/ipykernel_68533/662710321.py:2: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(theta))


In [21]:
np.log(x)

/var/folders/sb/30311bq16l911lpqttfpzgdw0000gn/T/ipykernel_68533/1277889159.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [22]:
np.log10(x)

/var/folders/sb/30311bq16l911lpqttfpzgdw0000gn/T/ipykernel_68533/1114196279.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(x)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [23]:
np.expm1(x)

array([0.00000000e+00, 1.71828183e+00, 6.38905610e+00, 1.90855369e+01,
       5.35981500e+01, 1.47413159e+02, 4.02428793e+02, 1.09563316e+03,
       2.97995799e+03, 8.10208393e+03])

## Investigar
- reduce
- accumulate
- outer

In [24]:
import pandas as pd

In [29]:
data = pd.read_csv('../dataset/covid-variants.csv')

In [30]:
data

location        date         variant  num_sequences  perc_sequences  \
0         Angola  2020-07-06           Alpha              0             0.0   
1         Angola  2020-07-06       B.1.1.277              0             0.0   
2         Angola  2020-07-06       B.1.1.302              0             0.0   
3         Angola  2020-07-06       B.1.1.519              0             0.0   
4         Angola  2020-07-06         B.1.160              0             0.0   
...          ...         ...             ...            ...             ...   
100411  Zimbabwe  2021-11-01         Omicron              0             0.0   
100412  Zimbabwe  2021-11-01   S:677H.Robin1              0             0.0   
100413  Zimbabwe  2021-11-01  S:677P.Pelican              0             0.0   
100414  Zimbabwe  2021-11-01          others              0             0.0   
100415  Zimbabwe  2021-11-01         non_who              0             0.0   

        num_sequences_total  
0                         3  
1                         3  
2                         3  
3                         3  
4                         3  
...                     ...  
100411                    6  
100412                    6  
100413                    6  
100414                    6  
100415                    6  

[100416 rows x 6 columns]

In [31]:
num_secs = data['num_sequences']

In [32]:
num_secs

0         0
1         0
2         0
3         0
4         0
         ..
100411    0
100412    0
100413    0
100414    0
100415    0
Name: num_sequences, Length: 100416, dtype: int64

In [34]:
%timeit sum(num_secs)
%timeit np.sum(num_secs)

3.39 ms ± 207 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
58 µs ± 983 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [36]:
maximo = np.max(num_secs)
maximo

142280

In [38]:
minimo = np.min(num_secs)
minimo

0

In [39]:
num_secs.min()

0

In [40]:
num_secs.max()

142280

In [43]:
print(np.mean(num_secs))
print(np.std(num_secs))
print(np.median(num_secs))
print(np.percentile(num_secs,1))
print(np.all(num_secs))

72.17167582855322
1669.2538575425174
0.0
0.0
False
