# Broadcasting

In [2]:
import numpy as np

In [3]:
a = np.array([4,3,2])
b = np.array([2,3,4])

In [4]:
a+b

array([6, 6, 6])

In [5]:
a+5

array([9, 8, 7])

In [6]:
a = np.ones((3,3))

In [7]:
a+5

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [15]:
a = np.arange(3)
b = np.arange(3)[:,np.newaxis]
print(a)
print(b)

[0 1]
[[0]
 [1]
 [2]]


In [16]:
a+b

array([[0, 1],
       [1, 2],
       [2, 3]])

In [20]:
m = np.ones((3,2))

In [21]:
a = np.arange(3)

In [22]:
m

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
a

array([0, 1, 2])

In [24]:
m + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [ ]:
## Regresar a ejemplos.